package com.zero.zClanSystem.gui;

public enum GUIType {
    MAIN_MENU_CLAN,
    MAIN_MENU_NO_CLAN,
    CREATE_CLAN,
    ADMIN_MENU,
    ADMIN_FORCE_DISBAND,
    ADMIN_FORCE_DISBAND_APPLY,
    ADMIN_KICK_PLAYER,
    ADMIN_CLAN_SELECT_MODIFY,
    ADMIN_CLAN_MODIFY,
    ADMIN_CLAN_MODIFY_COLOR,
    TOP_CLANS_LIST,
    TOP_CLANS_ALL_RANK_LIST,
    TOP_CLAN_STATS,
    MY_CLAN_MENU,
    MY_CLAN_STATS,
    MY_CLAN_SETTINGS,
    MY_CLAN_HOME,
    MY_CLAN_MEMBERS,
    MY_CLAN_MEMBERS_LIST,
    MY_CLAN_MEMBER_OPTIONS,
    MY_CLAN_SETTINGS_DISBAND,
    MY_CLAN_TRANSFER_OWNERSHIP,
    MY_CLAN_INVITES,
    CLAN_INVITES_MENU
}